import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path


class ObsidianPluginMetadataTests(unittest.TestCase):
    def test_manifest_declares_desktop_plugin(self) -> None:
        manifest = json.loads(Path("manifest.json").read_text(encoding="utf-8"))

        self.assertEqual(manifest["id"], "word-history")
        self.assertEqual(manifest["name"], "Word History")
        self.assertEqual(manifest["version"], "0.1.0")
        self.assertTrue(manifest["isDesktopOnly"])
        self.assertIn("SVG", manifest["description"])

    def test_plugin_entrypoint_preserves_minimal_settings_and_commands(self) -> None:
        main_js = Path("main.js").read_text(encoding="utf-8")
        source_ts = Path("src/main.ts").read_text(encoding="utf-8")
        package_json = json.loads(Path("package.json").read_text(encoding="utf-8"))

        self.assertTrue(Path("src/main.ts").exists())
        self.assertTrue(Path("tsconfig.json").exists())
        self.assertTrue(Path("esbuild.config.mjs").exists())
        self.assertTrue(Path("package-lock.json").exists())
        self.assertIn("typescript", package_json["devDependencies"])
        self.assertIn("esbuild", package_json["devDependencies"])
        self.assertIn("obsidian", package_json["devDependencies"])
        self.assertIn("tsc -noEmit", package_json["scripts"]["build"])
        self.assertIn("esbuild.config.mjs production", package_json["scripts"]["build"])
        self.assertIn("node esbuild.config.mjs", package_json["scripts"]["dev"])
        self.assertIn("dist/word-history", package_json["scripts"]["package"])
        self.assertIn("word-history-v$VERSION.zip", package_json["scripts"]["package"])
        self.assertIn("scripts/install_plugin.sh", package_json["scripts"]["install:plugin"])
        self.assertIn("THIS IS A GENERATED/BUNDLED FILE BY ESBUILD", main_js)
        self.assertNotIn("@ts-nocheck", source_ts)
        self.assertIn("outputPath", main_js)
        self.assertIn("updateMode", main_js)
        self.assertIn("intervalDays", main_js)
        self.assertIn("generate-word-history-chart", main_js)
        self.assertIn("check-word-history-git-changes", main_js)
        self.assertIn("buildWordHistory", main_js)
        self.assertIn("runPreflight", main_js)
        self.assertIn("Copy Obsidian embed", main_js)
        self.assertIn("Reset cache", main_js)
        self.assertIn("noImplicitAny", Path("tsconfig.json").read_text(encoding="utf-8"))
        self.assertTrue(Path("src/generator.ts").exists())
        self.assertTrue(Path("src/preflight.ts").exists())
        self.assertTrue(Path("src/settings.ts").exists())
        self.assertNotIn("generate_chart.sh", main_js)
        self.assertNotIn("python3", main_js)
        self.assertNotIn("obsidian_word_history", main_js)
        self.assertNotIn("generate_chart.sh", source_ts)
        self.assertNotIn("python3", source_ts)
        self.assertNotIn("obsidian_word_history", source_ts)
        self.assertNotIn("/Users/", main_js)
        self.assertNotIn("Obsidian" + " Notes", main_js)
        self.assertNotIn("/Users/", source_ts)
        self.assertNotIn("Obsidian" + " Notes", source_ts)


    def test_docs_describe_beta_first_success_path(self) -> None:
        chinese = Path("README.md").read_text(encoding="utf-8")
        english = Path("README.en.md").read_text(encoding="utf-8")

        for text in (chinese, english):
            self.assertIn("GitHub Release", text)
            self.assertIn("BRAT", text)
            self.assertIn("Reference/chart.svg", text)
            self.assertIn("`git`", text)
            self.assertIn("Obsidian Community Plugin", text)
        self.assertIn("字数趋势", chinese)
        self.assertIn("single SVG", english)

    def test_release_package_zip_contains_runtime_files_only(self) -> None:
        package_json = json.loads(Path("package.json").read_text(encoding="utf-8"))
        self.assertIn("zip", package_json["scripts"]["package"])
        completed = subprocess.run(["npm", "run", "package"], check=False, capture_output=True, text=True)
        self.assertEqual(completed.returncode, 0, completed.stderr)
        package_dir = Path("dist/word-history")
        self.assertTrue((package_dir / "main.js").exists())
        self.assertTrue((package_dir / "manifest.json").exists())
        self.assertTrue((package_dir / "versions.json").exists())
        self.assertFalse((package_dir / "src").exists())
        self.assertFalse((package_dir / "package.json").exists())

    def test_install_script_creates_minimal_plugin_runtime(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            vault = Path(tmpdir) / "vault"
            vault.mkdir()
            plugin_dir = vault / ".obsidian" / "plugins" / "word-history"
            plugin_dir.mkdir(parents=True)
            (plugin_dir / "data.json").write_text('{"outputPath":"Reference/chart.svg"}', encoding="utf-8")
            (plugin_dir / ".cache").mkdir()
            (plugin_dir / ".cache" / "word-history-cache.json").write_text("{}", encoding="utf-8")
            (plugin_dir / "src").mkdir()
            (plugin_dir / "src" / "main.ts").write_text("stale source", encoding="utf-8")
            (plugin_dir / "package.json").write_text("{}", encoding="utf-8")

            completed = subprocess.run(
                ["bash", "scripts/install_plugin.sh", str(vault), "--skip-build"],
                check=False,
                capture_output=True,
                text=True,
            )
            self.assertEqual(completed.returncode, 0, completed.stderr)
            installed = {path.name for path in plugin_dir.iterdir()}
            self.assertIn("main.js", installed)
            self.assertIn("manifest.json", installed)
            self.assertIn("versions.json", installed)
            self.assertIn("data.json", installed)
            self.assertIn(".cache", installed)
            self.assertNotIn("src", installed)
            self.assertNotIn("package.json", installed)
            self.assertNotIn("tests", installed)
            self.assertEqual((plugin_dir / "data.json").read_text(encoding="utf-8"), '{"outputPath":"Reference/chart.svg"}')

    def test_js_generator_builds_svg_and_incremental_cache_without_python(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            repo = Path(tmpdir) / "vault"
            output_svg = Path(tmpdir) / "chart.svg"
            cache_json = Path(tmpdir) / "cache.json"
            repo.mkdir()
            self._git(repo, "init")
            self._git(repo, "config", "user.name", "Test User")
            self._git(repo, "config", "user.email", "test@example.com")

            (repo / "note.md").write_text("hello 世界", encoding="utf-8")
            self._commit(repo, "initial", "2026-01-01T08:00:00+00:00")

            first = self._run_js_generator(repo, output_svg, cache_json)
            self.assertEqual(first["currentTotalWords"], 3)
            self.assertEqual(first["wordsAddedSinceLastRun"], 3)
            svg = output_svg.read_text(encoding="utf-8")
            self.assertIn("Word History", svg)
            self.assertIn('class="xaxis"', svg)
            self.assertIn('class="yaxis"', svg)
            self.assertIn('class="chart-line"', svg)
            self.assertTrue(cache_json.exists())

            second = self._run_js_generator(repo, output_svg, cache_json)
            self.assertEqual(second["currentTotalWords"], 3)
            self.assertEqual(second["wordsAddedSinceLastRun"], 0)

            (repo / "note.md").write_text("hello brave 世界", encoding="utf-8")
            self._commit(repo, "expand", "2026-01-02T08:00:00+00:00")
            third = self._run_js_generator(repo, output_svg, cache_json)
            self.assertEqual(third["currentTotalWords"], 4)
            self.assertEqual(third["wordsAddedSinceLastRun"], 1)


    def test_preflight_reports_common_first_run_failures(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            non_repo = Path(tmpdir) / "not-a-repo"
            non_repo.mkdir()
            non_repo_result = self._run_js_preflight(non_repo, non_repo / "Reference" / "chart.svg")
            self.assertFalse(non_repo_result["ok"])
            self.assertTrue(any(check["key"] == "repo" and not check["ok"] for check in non_repo_result["checks"]))

            empty_repo = Path(tmpdir) / "empty"
            empty_repo.mkdir()
            self._git(empty_repo, "init")
            empty_result = self._run_js_preflight(empty_repo, empty_repo / "Reference" / "chart.svg")
            self.assertFalse(empty_result["ok"])
            self.assertTrue(any(check["key"] == "head" and not check["ok"] for check in empty_result["checks"]))

            blocked_repo = Path(tmpdir) / "blocked"
            blocked_repo.mkdir()
            self._git(blocked_repo, "init")
            self._git(blocked_repo, "config", "user.name", "Test User")
            self._git(blocked_repo, "config", "user.email", "test@example.com")
            (blocked_repo / "note.md").write_text("hello", encoding="utf-8")
            self._commit(blocked_repo, "initial", "2026-01-01T08:00:00+00:00")
            (blocked_repo / "Reference").write_text("not a directory", encoding="utf-8")
            blocked_result = self._run_js_preflight(blocked_repo, blocked_repo / "Reference" / "chart.svg")
            self.assertFalse(blocked_result["ok"])
            self.assertTrue(any(check["key"] == "output" and not check["ok"] for check in blocked_result["checks"]))

    def _run_js_preflight(self, repo: Path, output_svg: Path) -> dict:
        node_code = r"""
const Module = require("module");
const originalLoad = Module._load;
Module._load = function(request, parent, isMain) {
  if (request === "obsidian") {
    return {
      Notice: class {},
      Plugin: class {},
      PluginSettingTab: class {},
      Setting: class {},
    };
  }
  return originalLoad.apply(this, arguments);
};
const plugin = require(process.argv[1]);
plugin.__test.runPreflight(process.argv[2], process.argv[3])
  .then((result) => console.log(JSON.stringify(result)))
  .catch((error) => {
    console.error(error.stack || error.message);
    process.exit(1);
  });
"""
        completed = subprocess.run(
            ["node", "-e", node_code, str(Path.cwd() / "main.js"), str(repo), str(output_svg)],
            check=False,
            capture_output=True,
            text=True,
        )
        self.assertEqual(completed.returncode, 0, completed.stderr)
        return json.loads(completed.stdout)

    def _run_js_generator(self, repo: Path, output_svg: Path, cache_json: Path) -> dict:
        node_code = r"""
const Module = require("module");
const originalLoad = Module._load;
Module._load = function(request, parent, isMain) {
  if (request === "obsidian") {
    return {
      Notice: class {},
      Plugin: class {},
      PluginSettingTab: class {},
      Setting: class {},
    };
  }
  return originalLoad.apply(this, arguments);
};
const plugin = require(process.argv[1]);
plugin.__test.buildWordHistory(process.argv[2], process.argv[3], process.argv[4])
  .then((result) => {
    console.log(JSON.stringify({
      wordsAddedSinceLastRun: result.wordsAddedSinceLastRun,
      currentTotalWords: result.currentTotalWords,
    }));
  })
  .catch((error) => {
    console.error(error.stack || error.message);
    process.exit(1);
  });
"""
        completed = subprocess.run(
            [
                "node",
                "-e",
                node_code,
                str(Path.cwd() / "main.js"),
                str(repo),
                str(output_svg),
                str(cache_json),
            ],
            check=False,
            capture_output=True,
            text=True,
        )
        self.assertEqual(completed.returncode, 0, completed.stderr)
        return json.loads(completed.stdout)

    def _commit(self, repo: Path, message: str, timestamp: str) -> None:
        env = os.environ.copy()
        env["GIT_AUTHOR_DATE"] = timestamp
        env["GIT_COMMITTER_DATE"] = timestamp
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True, env=env)
        subprocess.run(["git", "-C", str(repo), "commit", "-m", message], check=True, env=env, capture_output=True)

    def _git(self, repo: Path, *args: str) -> str:
        completed = subprocess.run(
            ["git", "-C", str(repo), *args],
            check=True,
            capture_output=True,
            text=True,
        )
        return completed.stdout


if __name__ == "__main__":
    unittest.main()
